server:
  phone: "+86XXXXXXXXXXX"
  title: "XXX早上好"
  end: "记得按时吃饭哦(￣^￣)ゞ"
  form: "bogeia"

weather:
  host: "https://api.caiyunapp.com"
  token: "XXXXXXXXXX"
  version: "v2.6"
  location: "104.12312,124.12312" # 经纬度
  timeout: "3s"

sentence:
  iciba: "http://open.iciba.com/dsapi/" # 金山词霸 每日一句
  shadiao: "https://api.shadiao.pro/chp" # 沙雕 彩虹屁
  shanbay: "https://apiv3.shanbay.com/weapps/dailyquote/quote/" # 扇贝英语 每日一句
  timeout: "3s"